### ISSUE TITLE
Untangle the edges

### ISSUE THREAD

**Issue by seachicken** [seachicken/inga-ui#6]
Related declarations should be sorted side-by-side whenever possible.

<img width="320" alt="image" src="https://github.com/seachicken/inga-ui/assets/5178598/3d1c50b4-1884-4b7c-96ca-d9ba6bbc667a">

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me

**Comment by seachicken** [comment]
Ok, thank you

**Comment by lakshyeahh** [comment]
Is there any contribution.md or any doc which can help me.

**Comment by seachicken** [comment]
Oh, I was so unkind. I created [CONTRIBUTING.md](https://github.com/seachicken/inga-ui/blob/main/CONTRIBUTING.md).
But, since this repository is a tool for visualizing [Inga](https://github.com/seachicken/inga)'s results, it may require more than understanding the overall specifications from this alone.
I will attach a sample report.json to run inga-ui alone. [report.json.zip](https://github.com/user-attachments/files/17242785/report.json.zip)

**Comment by seachicken** [comment]
Hi, There has been no response, so I will remove the assignment

**Comment by seachicken** [comment]
As a user, it is easier to understand if the order of functions is arranged according to a set rule, such as the order of definition or alphabetical order. Since it is better not to dynamically adjust the order to avoid overlapping relationships, I will close this issue.
